# Generated by Django 5.0.6 on 2025-01-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PenjualanKerudung',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('brand', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=100)),
                ('bahan', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terjual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingDataLatih',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=100)),
                ('bahan', models.CharField(max_length=100)),
                ('harga', models.CharField(max_length=100)),
                ('terjual', models.CharField(max_length=100)),
            ],
        ),
    ]
